import '../styles/globals.css'
import styles from '../styles/landingPage/landingPage.module.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className={styles.page}>
          {children}
        </div>
        <footer>
          some stuff
        </footer>
      </body>
    </html>
  )
}
