"""remove compound FK on vote

Revision ID: 3ee9a76f3481
Revises: a1b2c3d4e5f6
Create Date: 2026-05-24 20:53:15.185790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ee9a76f3481'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_vote_proposal_session'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'movie_proposal', ['proposal_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_vote_proposal_session'), 'movie_proposal', ['proposal_id', 'session_id'], ['id', 'session_id'], ondelete='CASCADE')

    # ### end Alembic commands ###
