"""add movies cache table

Revision ID: 8f6a04744227
Revises: 18e4e5aadd77
Create Date: 2026-05-20 11:30:02.708285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f6a04744227'
down_revision = '18e4e5aadd77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('original_title', sa.String(length=512), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('poster_url', sa.String(length=512), nullable=True),
    sa.Column('backdrop_url', sa.String(length=512), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('runtime_minutes', sa.Integer(), nullable=True),
    sa.Column('genres', sa.JSON(), nullable=False),
    sa.Column('popularity', sa.Float(), nullable=True),
    sa.Column('vote_average', sa.Float(), nullable=True),
    sa.Column('original_language', sa.String(length=10), nullable=True),
    sa.Column('cached_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movies_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_movies_tmdb_id'), ['tmdb_id'], unique=True)

    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('invite_code', sa.String(length=16), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_code')
    )
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_created_by_id'), ['created_by_id'], unique=False)

    op.create_table('group_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'member', name='group_member_role'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'group_id', name='uq_group_member_user_group')
    )
    with op.batch_alter_table('group_member', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_member_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_member_user_id'), ['user_id'], unique=False)

    op.create_table('movie_night_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('open', 'voting', 'decided', 'closed', name='session_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movie_night_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movie_night_session_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movie_night_session_group_id'), ['group_id'], unique=False)

    op.create_table('food_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['movie_night_session.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('food_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_food_item_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_item_user_id'), ['user_id'], unique=False)

    op.create_table('movie_proposal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('proposed_by_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('poster_url', sa.String(length=512), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('runtime_minutes', sa.Integer(), nullable=True),
    sa.Column('proposed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proposed_by_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['movie_night_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'session_id', name='uq_proposal_id_session'),
    sa.UniqueConstraint('proposed_by_id', 'session_id', name='uq_proposal_user_session')
    )
    with op.batch_alter_table('movie_proposal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movie_proposal_proposed_by_id'), ['proposed_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movie_proposal_session_id'), ['session_id'], unique=False)
        batch_op.create_index('ix_proposal_tmdb_session', ['tmdb_id', 'session_id'], unique=True, postgresql_where=sa.text('tmdb_id IS NOT NULL'))

    op.create_table('session_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('winning_proposal_id', sa.Integer(), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['movie_night_session.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winning_proposal_id', 'session_id'], ['movie_proposal.id', 'movie_proposal.session_id'], name='fk_result_proposal_session', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    with op.batch_alter_table('session_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_result_winning_proposal_id'), ['winning_proposal_id'], unique=False)

    op.create_table('vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('voted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id', 'session_id'], ['movie_proposal.id', 'movie_proposal.session_id'], name='fk_vote_proposal_session', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['movie_night_session.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'session_id', name='uq_vote_user_session')
    )
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vote_proposal_id'), ['proposal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vote_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vote_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vote_user_id'))
        batch_op.drop_index(batch_op.f('ix_vote_session_id'))
        batch_op.drop_index(batch_op.f('ix_vote_proposal_id'))

    op.drop_table('vote')
    with op.batch_alter_table('session_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_result_winning_proposal_id'))

    op.drop_table('session_result')
    with op.batch_alter_table('movie_proposal', schema=None) as batch_op:
        batch_op.drop_index('ix_proposal_tmdb_session', postgresql_where=sa.text('tmdb_id IS NOT NULL'))
        batch_op.drop_index(batch_op.f('ix_movie_proposal_session_id'))
        batch_op.drop_index(batch_op.f('ix_movie_proposal_proposed_by_id'))

    op.drop_table('movie_proposal')
    with op.batch_alter_table('food_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_food_item_user_id'))
        batch_op.drop_index(batch_op.f('ix_food_item_session_id'))

    op.drop_table('food_item')
    with op.batch_alter_table('movie_night_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movie_night_session_group_id'))
        batch_op.drop_index(batch_op.f('ix_movie_night_session_created_by_id'))

    op.drop_table('movie_night_session')
    with op.batch_alter_table('group_member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_member_user_id'))
        batch_op.drop_index(batch_op.f('ix_group_member_group_id'))

    op.drop_table('group_member')
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_created_by_id'))

    op.drop_table('group')
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movies_tmdb_id'))
        batch_op.drop_index(batch_op.f('ix_movies_title'))

    op.drop_table('movies')
    # ### end Alembic commands ###
