"""restore compound fk on vote

Revision ID: e6cc35f98219
Revises: 94142c319da2
Create Date: 2026-08-28 22:20:09.410323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6cc35f98219'
down_revision = '94142c319da2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('vote_proposal_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key('fk_vote_proposal_session', 'movie_proposal', ['proposal_id', 'session_id'], ['id', 'session_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.drop_constraint('fk_vote_proposal_session', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('vote_proposal_id_fkey'), 'movie_proposal', ['proposal_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
